import { getAuth } from "@clerk/express";
import { and, desc, eq, or } from "drizzle-orm";
import { Router, type IRouter, type Request, type Response } from "express";
import * as api from "@workspace/api-zod";
import { answers, comments, db, discussionComments, discussions, marketplaceListings, questions, userProfiles } from "@workspace/db";
import { deleteDiscussionGraph, deleteQuestionGraph, viewerFor, visibleAnswer, visibleContent, visibleDiscussion, visibleListing, visibleQuestion } from "../services/contentAccess";

const router: IRouter = Router();
const schema = (name: string, value: unknown) => (api as unknown as Record<string, { parse(value: unknown): any; safeParse(value: unknown): any }>)[name];
const id = (req: Request, name: string) => schema(name, req.params).safeParse(req.params);
function user(req: Request, res: Response) { const value = getAuth(req).userId; if (!value) { res.status(401).json({ error: "Authentication required" }); return null; } return value; }
const q = (r: any) => ({ ...r, timestamp: r.createdAt.getTime(), acceptedAnswerId: r.acceptedAnswerId ?? null });
const a = (r: any) => ({ ...r, timestamp: r.createdAt.getTime() });
const d = (r: any) => ({ ...r, timestamp: r.createdAt.getTime(), title: r.title ?? null });
const l = (r: any) => ({ ...r, price: Number(r.price), timestamp: r.createdAt.getTime() });
const c = (r: any) => ({ ...r, timestamp: r.createdAt.getTime() });
function bad(res: Response, parsed: any) { if (!parsed.success) { res.status(400).json({ error: parsed.error.message }); return true; } return false; }
async function author(_body: any, userId: string) { const profile=(await db.select().from(userProfiles).where(eq(userProfiles.userId,userId)).limit(1))[0]; return { userId, userName: profile?.displayName ?? "Member", userRole: profile?.accountType ?? "Car Owner", userSpecialization: profile?.specialization ?? "", userVerified: profile?.verified === true }; }
async function toggle(table: any, parsed: any, userId: string, map: (row: any) => any, output: string, res: Response) {
  const row = (await db.select().from(table).where(eq(table.id, parsed.data.id)).limit(1))[0]; if (!row) { res.status(404).json({ error: "Content not found" }); return; }
  const voters = row.upvotedBy.includes(userId) ? row.upvotedBy.filter((x: string) => x !== userId) : [...row.upvotedBy, userId];
  const [updated] = await db.update(table).set({ upvotedBy: voters, upvotes: voters.length, updatedAt: new Date() }).where(eq(table.id, row.id)).returning();
  res.json(schema(output, null).parse(map(updated)));
}

router.get("/questions", async (req, res) => { const u=user(req,res); if(!u)return; const p=schema("ListQuestionsQueryParams",req.query).safeParse(req.query); if(bad(res,p))return; const rows=await db.select().from(questions).orderBy(desc(questions.createdAt)).limit(p.data.limit).offset(p.data.offset); res.json(schema("ListQuestionsResponse",null).parse({items:rows.map(q),limit:p.data.limit,offset:p.data.offset})); });
router.post("/questions", async (req,res) => { const u=user(req,res), p=schema("CreateQuestionBody",req.body).safeParse(req.body); if(!u||bad(res,p))return; const [row]=await db.insert(questions).values({...p.data,...await author(p.data,u)}).returning(); res.status(201).json(schema("GetQuestionResponse",null).parse(q(row))); });
router.get("/questions/:id", async(req,res)=>{const u=user(req,res),p=id(req,"GetQuestionParams");if(!u||bad(res,p))return;const row=await visibleQuestion(p.data.id,await viewerFor(u));if(!row){res.status(404).json({error:"Question not found"});return}res.json(schema("GetQuestionResponse",null).parse(q(row)));});
router.delete("/questions/:id",async(req,res)=>{const u=user(req,res),p=id(req,"DeleteQuestionParams");if(!u||bad(res,p))return;const row=await deleteQuestionGraph(p.data.id,u);if(!row){res.status(404).json({error:"Question not found"});return}res.status(204).send()});
router.post("/questions/:id/upvote",async(req,res)=>{const u=user(req,res),p=id(req,"UpvoteQuestionParams");if(!u||bad(res,p))return;await toggle(questions,p,u,q,"UpvoteQuestionResponse",res)});
router.get("/questions/:id/answers",async(req,res)=>{const u=user(req,res),p=id(req,"ListQuestionAnswersParams");if(!u||bad(res,p))return;const rows=await db.select().from(answers).where(eq(answers.questionId,p.data.id)).orderBy(answers.createdAt);res.json(schema("ListQuestionAnswersResponse",null).parse({items:rows.map(a)}))});
router.post("/questions/:id/answers",async(req,res)=>{const u=user(req,res),p=id(req,"CreateAnswerParams"),b=schema("CreateAnswerBody",req.body).safeParse(req.body);if(!u||bad(res,p)||bad(res,b))return;if(!await visibleQuestion(p.data.id,await viewerFor(u))){res.status(404).json({error:"Question not found"});return}const [row]=await db.insert(answers).values({questionId:p.data.id,content:b.data.content,...await author(b.data,u)}).returning();res.status(201).json(schema("GetAnswerResponse",null).parse(a(row)))});
router.post("/questions/:questionId/answers/:answerId/accept",async(req,res)=>{const u=user(req,res),p=id(req,"AcceptQuestionAnswerParams");if(!u||bad(res,p))return;const question=(await db.select().from(questions).where(and(eq(questions.id,p.data.questionId),eq(questions.userId,u))).limit(1))[0];const answer=question&&(await db.select().from(answers).where(and(eq(answers.id,p.data.answerId),eq(answers.questionId,question.id))).limit(1))[0];if(!answer){res.status(404).json({error:"Question or answer not found"});return}await db.update(answers).set({isAccepted:false}).where(eq(answers.questionId,question.id));const [updated]=await db.update(answers).set({isAccepted:true}).where(eq(answers.id,answer.id)).returning();await db.update(questions).set({acceptedAnswerId:answer.id,updatedAt:new Date()}).where(eq(questions.id,question.id));res.json(schema("AcceptQuestionAnswerResponse",null).parse(a(updated)))});
router.get("/answers/:id",async(req,res)=>{const u=user(req,res),p=id(req,"GetAnswerParams");if(!u||bad(res,p))return;const row=await visibleAnswer(p.data.id,await viewerFor(u));if(!row){res.status(404).json({error:"Answer not found"});return}res.json(schema("GetAnswerResponse",null).parse(a(row)))});
router.delete("/answers/:id",async(req,res)=>{const u=user(req,res),p=id(req,"DeleteAnswerParams");if(!u||bad(res,p))return;const [r]=await db.delete(answers).where(and(eq(answers.id,p.data.id),eq(answers.userId,u))).returning();if(!r){res.status(404).json({error:"Answer not found"});return}res.status(204).send()});
router.post("/answers/:id/upvote",async(req,res)=>{const u=user(req,res),p=id(req,"UpvoteAnswerParams");if(!u||bad(res,p))return;await toggle(answers,p,u,a,"UpvoteAnswerResponse",res)});
async function parentExists(parentId:number,isAnswer:boolean){return Boolean((await db.select({id:isAnswer?answers.id:questions.id}).from(isAnswer?answers:questions).where(eq(isAnswer?answers.id:questions.id,parentId)).limit(1))[0]);}
function commentRoutes(path:string,isAnswer:boolean,params:string,listResponse:string,createBody:string) {
  router.get(path,async(req,res)=>{const u=user(req,res),p=id(req,params);if(!u||bad(res,p))return;const rows=await db.select().from(comments).where(and(eq(comments.questionOrAnswerId,p.data.id),eq(comments.isAnswer,isAnswer))).orderBy(comments.createdAt);res.json(schema(listResponse,null).parse({items:rows.map(c)}))});
  router.post(path,async(req,res)=>{const u=user(req,res),p=id(req,params),b=schema(createBody,req.body).safeParse(req.body);if(!u||bad(res,p)||bad(res,b))return;if(!await parentExists(p.data.id,isAnswer)){res.status(404).json({error:"Parent not found"});return}const [r]=await db.insert(comments).values({questionOrAnswerId:p.data.id,isAnswer,userId:u,userName:b.data.userName,content:b.data.content}).returning();res.status(201).json(schema(listResponse,null).parse({items:[c(r)]}).items[0])});
}
commentRoutes("/questions/:id/comments",false,"ListQuestionCommentsParams","ListQuestionCommentsResponse","CreateQuestionCommentBody");
commentRoutes("/answers/:id/comments",true,"ListAnswerCommentsParams","ListAnswerCommentsResponse","CreateAnswerCommentBody");
router.get("/discussions/:id/comments",async(req,res)=>{const u=user(req,res),p=id(req,"ListDiscussionCommentsParams");if(!u||bad(res,p))return;const rows=await db.select().from(discussionComments).where(eq(discussionComments.postId,p.data.id)).orderBy(discussionComments.createdAt);res.json(schema("ListDiscussionCommentsResponse",null).parse({items:rows.map(c)}))});
router.post("/discussions/:id/comments",async(req,res)=>{const u=user(req,res),p=id(req,"CreateDiscussionCommentParams"),b=schema("CreateDiscussionCommentBody",req.body).safeParse(req.body);if(!u||bad(res,p)||bad(res,b))return;const post=(await db.select().from(discussions).where(eq(discussions.id,p.data.id)).limit(1))[0];if(!post||post.isProCircle&&post.userId!==u){res.status(404).json({error:"Discussion not found"});return}const [r]=await db.insert(discussionComments).values({postId:p.data.id,userId:u,userName:b.data.userName,content:b.data.content}).returning();res.status(201).json(schema("ListDiscussionCommentsResponse",null).parse({items:[c(r)]}).items[0])});

router.get("/discussions",async(req,res)=>{const u=user(req,res),p=schema("ListDiscussionsQueryParams",req.query).safeParse(req.query);if(!u||bad(res,p))return;const rows=await db.select().from(discussions).where(or(eq(discussions.isProCircle,false),eq(discussions.userId,u))).orderBy(desc(discussions.createdAt)).limit(p.data.limit).offset(p.data.offset);res.json(schema("ListDiscussionsResponse",null).parse({items:rows.map(d),limit:p.data.limit,offset:p.data.offset}))});
router.post("/discussions",async(req,res)=>{const u=user(req,res),p=schema("CreateDiscussionBody",req.body).safeParse(req.body);if(!u||bad(res,p))return;const [r]=await db.insert(discussions).values({...p.data,...await author(p.data,u)}).returning();res.status(201).json(schema("GetDiscussionResponse",null).parse(d(r)))});
router.get("/discussions/:id",async(req,res)=>{const u=user(req,res),p=id(req,"GetDiscussionParams");if(!u||bad(res,p))return;const r=await visibleDiscussion(p.data.id,await viewerFor(u));if(!r){res.status(404).json({error:"Discussion not found"});return}res.json(schema("GetDiscussionResponse",null).parse(d(r)))});
router.delete("/discussions/:id",async(req,res)=>{const u=user(req,res),p=id(req,"DeleteDiscussionParams");if(!u||bad(res,p))return;const r=await deleteDiscussionGraph(p.data.id,u);if(!r){res.status(404).json({error:"Discussion not found"});return}res.status(204).send()});
router.post("/discussions/:id/upvote",async(req,res)=>{const u=user(req,res),p=id(req,"UpvoteDiscussionParams");if(!u||bad(res,p))return;await toggle(discussions,p,u,d,"UpvoteDiscussionResponse",res)});

router.get("/listings",async(req,res)=>{const u=user(req,res),p=schema("ListListingsQueryParams",req.query).safeParse(req.query);if(!u||bad(res,p))return;const rows=await db.select().from(marketplaceListings).where(or(eq(marketplaceListings.isApproved,true),eq(marketplaceListings.userId,u))).orderBy(desc(marketplaceListings.createdAt)).limit(p.data.limit).offset(p.data.offset);res.json(schema("ListListingsResponse",null).parse({items:rows.map(l),limit:p.data.limit,offset:p.data.offset}))});
router.post("/listings",async(req,res)=>{const u=user(req,res),p=schema("CreateListingBody",req.body).safeParse(req.body);if(!u||bad(res,p))return;const [r]=await db.insert(marketplaceListings).values({...p.data,price:String(p.data.price),...await author(p.data,u),userPhone:p.data.userPhone??""}).returning();res.status(201).json(schema("GetListingResponse",null).parse(l(r)))});
router.get("/listings/:id",async(req,res)=>{const u=user(req,res),p=id(req,"GetListingParams");if(!u||bad(res,p))return;const r=await visibleListing(p.data.id,await viewerFor(u));if(!r){res.status(404).json({error:"Listing not found"});return}res.json(schema("GetListingResponse",null).parse(l(r)))});
router.delete("/listings/:id",async(req,res)=>{const u=user(req,res),p=id(req,"DeleteListingParams");if(!u||bad(res,p))return;const [r]=await db.delete(marketplaceListings).where(and(eq(marketplaceListings.id,p.data.id),eq(marketplaceListings.userId,u))).returning();if(!r){res.status(404).json({error:"Listing not found"});return}res.status(204).send()});
for (const [path, param, body] of [["/listings/:id/approval","SetListingApprovalParams","SetListingApprovalBody"],["/listings/:id/featured","SetListingFeaturedParams","SetListingFeaturedBody"]] as const) router.patch(path,async(req,res)=>{const u=user(req,res),p=id(req,param),b=schema(body,req.body).safeParse(req.body);if(!u||bad(res,p)||bad(res,b))return;res.status(403).json({error:"Server-side administrator authorization is not configured"})});

export default router;